apiVersion: v1
kind: Service
metadata:
  name: tienda-backend-despacho
  namespace: ${EKS_NAMESPACE}
spec:
  selector:
    app: tienda-backend-despacho
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP