apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-backend-ventas
  namespace: inovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tienda-backend-ventas
  template:
    metadata:
      labels:
        app: tienda-backend-ventas
    spec:
      containers:
        - name: backend
          image: 042379109745.dkr.ecr.us-east-1.amazonaws.com/ecr-backend-ventas-inovatech:eks-v1
          ports:
            - containerPort: 8082
          env:
            - name: DB_IP_PRIVADA
              value: "tienda-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "despacho"
            - name: DB_USERNAME
              value: "alumno"
            - name: DB_PASSWORD
              value: "alumno123"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 15