apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ${EKS_NAMESPACE}
type: Opaque
stringData:
  DB_IP_PRIVADA: "${DB_IP_PRIVADA}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
